[package]
name = "lyricbot"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
crossbeam-channel = "0.5.13"
crossterm = "0.27.0"
dyn-clone = "1.0.17"
paste = "1.0.15"
ratatui = "0.26.3"
thiserror = "1.0.61"
